name: Test Project

on:
  push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          repository: gh-actions-udemy/second-action-react-js
          path: second-action-react-js
      - name: Print package file
        run: cat package.json