name: Test Project

on:
  push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Print package file
        run: cat second-action-react-js/package.json