name: Fourth Action Workflow
on: ...
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Output Github context
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"

      # Step 2: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 3: Example React.js build step (if required)
      - name: Install Dependencies
        working-directory: fourth-actions-gh-events
        run: npm ci

      # Step 4: Run test cases
      - name: Run tests
        working-directory: fourth-actions-gh-events
        run: npm test

      # Step 5: Build Project
      - name: Build Project
        working-directory: second-action-react-js
        run: npm run build

      # Step 6: Deploy
      - name: Deploy Project
        working-directory: second-action-react-js
        run: echo "Deploying..."