name: Second Action Workflow

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - "second-action-react-js/**"  # Trigger only on changes within this project

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install NodeJS
      - name: Install NodeJS
        working-directory: second-action-react-js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Example React.js build step (if required)
      - name: Install Dependencies
        working-directory: second-action-react-js
        run: npm ci

      # Step 4: Run test cases
      - name: Run tests
        working-directory: second-action-react-js
        run: npm test  
